using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using Model.Dao;
using Model.EF;
using System.Data.Entity;
namespace QL_CuocDT_WF
{
    public partial class UC_KH : DevExpress.XtraEditors.XtraUserControl
    {
        
        public UC_KH()
        {
            InitializeComponent();


      

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Model.EF.Model1 dbContext = new Model.EF.Model1();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.KhachHangs.Where(s => s.Status == true).Load();
            // This line of code is generated by Data Source Configuration Wizard
            khachHangsBindingSource.DataSource = dbContext.KhachHangs.Local.ToBindingList();
        }

        private void grid_KH_Click(object sender, EventArgs e)
        {
            txt_MaKH.Text = gridView1.GetRowCellValue(gridView1.FocusedRowHandle,"MaKH").ToString();
            txt_TenKH.Text = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "TenKH").ToString();
            txt_CMND.Text = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "CMND").ToString();
            txt_NN.Text = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "NgheNghiep").ToString();
            rtxt_DiaChi.Text = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "DiaChi").ToString();
        }
        public void refresh()
        {
            KhachHangDao kh = new KhachHangDao();
            khachHangsBindingSource.DataSource = kh.load();
        }
        private void khachHangsBindingSource_CurrentChanged(object sender, EventArgs e)
        {

        }


        private void khachHangsBindingSource_CurrentChanged_1(object sender, EventArgs e)
        {

        }

        private void bt_Them_Click(object sender, EventArgs e)
        {
            ThemKhachHang f = new ThemKhachHang(this);
            f.Show();
        }

        private void bt_Sua_Click(object sender, EventArgs e)
        {
            try
            {
                if (txt_MaKH.Text != "" || txt_CMND.Text != "" || txt_NN.Text != "" || txt_TenKH.Text != "")
                {
                    KhachHangDao kh = new KhachHangDao();
                    kh.suakhachhang(txt_MaKH.Text, txt_TenKH.Text, txt_CMND.Text, txt_NN.Text, rtxt_DiaChi.Text);
                    MessageBox.Show("sửa thành công");
                }
                else
                {
                    MessageBox.Show("Mời Nhập Đủ Thông Tin");
                }
                this.refresh();
            }
            catch (Exception ex)
            {
                MessageBox.Show("Đã có lỗi xảy ra");
            }
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            Model.EF.Model1 dbContext = new Model.EF.Model1();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.KhachHangs.Where(s => s.Status == true).Load();
            // This line of code is generated by Data Source Configuration Wizard
            khachHangsBindingSource.DataSource = dbContext.KhachHangs.Local.ToBindingList();
        }

        private void bt_Xoa_Click(object sender, EventArgs e)
        {
            if(MessageBox.Show("Bạn có thật sự muốn xóa?","Xóa Khách Hàng",MessageBoxButtons.YesNo,MessageBoxIcon.Question)==DialogResult.Yes)
            {
                KhachHangDao kh = new KhachHangDao();
                kh.xoakhachhang(txt_MaKH.Text);
                this.refresh();
                txt_CMND.Text = "";
                txt_MaKH.Text = "";
                txt_NN.Text = "";
                txt_TenKH.Text = "";
                rtxt_DiaChi.Text = "";
            }
            
        }

        private void textEdit1_TextChanged(object sender, EventArgs e)
        {
            gridView1.FindFilterText = textEdit1.Text;
        }
    }
}
