using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using Model.Dao;
using Model.EF;
using System.Data.Entity;
namespace QL_CuocDT_WF
{
    public partial class UC_LoaiCuoc : DevExpress.XtraEditors.XtraUserControl
    {
        
        public UC_LoaiCuoc()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Model.EF.Model1 dbContext = new Model.EF.Model1();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.LoaiCuocs.Where(s=>s.Status==true).Load();
            // This line of code is generated by Data Source Configuration Wizard
            loaiCuocsBindingSource.DataSource = dbContext.LoaiCuocs.Local.ToBindingList();
        }

        private void grid_KH_Click(object sender, EventArgs e)
        {
            txt_TGBD.EditValue =TimeSpan.Parse(gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "TG_BatDau").ToString());
            txt_TGKT.EditValue = TimeSpan.Parse(gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "TG_KetThuc").ToString());
            txt_GiaCuoc.Text = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "GiaCuoc").ToString();
        }

        private void khachHangsBindingSource_CurrentChanged(object sender, EventArgs e)
        {

        }
        Boolean kiemtra(string giacuoc)
        {
            float output;
            return float.TryParse(giacuoc, out output);
        }

        private void khachHangsBindingSource_CurrentChanged_1(object sender, EventArgs e)
        {

        }

        private void bt_Them_Click(object sender, EventArgs e)
        {
            ThemLoaiCuoc f = new ThemLoaiCuoc(this);
            f.Show();
        }
        public void refresh()
        {
            LoaiCuocDao lc = new LoaiCuocDao();
            loaiCuocsBindingSource.DataSource = lc.load();
        }
        private void bt_Sua_Click(object sender, EventArgs e)
        {
            
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            try
            {
                if(txt_TGBD.Text==""||txt_TGKT.Text==""||txt_GiaCuoc.Text=="")
                {
                    MessageBox.Show("Nhập đầy đủ thông tin");
                }
                else
                {
                    if(kiemtra(txt_GiaCuoc.Text)==true)
                    {
                        LoaiCuocDao lc = new LoaiCuocDao();
                        lc.sualoaicuoc(txt_TGBD.Text, txt_TGKT.Text, txt_GiaCuoc.Text);
                        MessageBox.Show("Sửa Thành Công");
                        this.refresh();
                    }
                    else
                    {
                        MessageBox.Show("Giá cước nhập số");
                    }
                }
            }
            catch(Exception ex)
            {
                MessageBox.Show("Đã có lỗi xảy ra");
            }
        }

        private void bt_Xoa_Click(object sender, EventArgs e)
        {
            if(MessageBox.Show("Bạn có thật sự muốn xóa?","Xóa Sim",MessageBoxButtons.YesNo,MessageBoxIcon.Question)==DialogResult.Yes)
            {
                LoaiCuocDao lc = new LoaiCuocDao();
                lc.XoaLoaiCuoc(txt_TGBD.Text, txt_TGKT.Text, txt_GiaCuoc.Text);
                MessageBox.Show("Xóa Thành Công");
                this.refresh();
                txt_GiaCuoc.Text = "";
                txt_TGBD.EditValue = new TimeSpan(00,00,00);
                txt_TGKT.EditValue =new TimeSpan(00,00,00) ;
            }
            
        }

        private void groupControl1_Paint(object sender, PaintEventArgs e)
        {

        }

        private void labelControl3_Click(object sender, EventArgs e)
        {

        }

        private void textEdit1_TextChanged(object sender, EventArgs e)
        {
            gridView1.FindFilterText = textEdit1.Text;
        }
    }
}
