using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using Model.Dao;
using Model.EF;
using System.Data.Entity;
namespace QL_CuocDT_WF
{
    public partial class UC_Sim : DevExpress.XtraEditors.XtraUserControl
    {
        public UC_Sim()
        {
            InitializeComponent();





            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Model.EF.Model1 dbContext = new Model.EF.Model1();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Sims.Load();
            // This line of code is generated by Data Source Configuration Wizard
            simsBindingSource.DataSource = dbContext.Sims.Local.ToBindingList();
        }
        Boolean kiemtrasdt(string sdt)
        {

            float output;
            return float.TryParse(sdt, out output);
        }
        private void grid_KH_Click(object sender, EventArgs e)
        {
            txt_MaSim.Text = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "MaSim").ToString();
            txt_SoSim.Text = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "SoSim").ToString();
        }

        private void khachHangsBindingSource_CurrentChanged(object sender, EventArgs e)
        {

        }


        private void khachHangsBindingSource_CurrentChanged_1(object sender, EventArgs e)
        {

        }
        public void refresh()
        {
            SimDao s = new SimDao();
            simsBindingSource.DataSource = s.loadgridcontrol();
        }
        private void bt_Them_Click(object sender, EventArgs e)
        {
            ThemSim f = new ThemSim(this);
            f.Show();
        }

        private void bt_Sua_Click(object sender, EventArgs e)
        {
            try
            {
                if(txt_MaSim.Text!=""||txt_SoSim.Text!="")
                {
                    if (kiemtrasdt(txt_SoSim.Text) == true)
                    {
                        SimDao s = new SimDao();
                        s.SuaSim(txt_MaSim.Text, txt_SoSim.Text);
                        MessageBox.Show("Sửa Thành Công");
                    }
                    else MessageBox.Show("số sim phải là số");
                }
                else
                {
                    MessageBox.Show("Mời Nhập Đủ Thông Tin");
                }
                this.refresh();
            }
            catch(Exception ex)
            {
                MessageBox.Show("Đã có lỗi xảy ra");
            }
            
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Model.EF.Model1 dbContext = new Model.EF.Model1();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Sims.Load();
            // This line of code is generated by Data Source Configuration Wizard
            simsBindingSource.DataSource = dbContext.Sims.Local.ToBindingList();
        }

        private void bt_Xoa_Click(object sender, EventArgs e)
        {
            if(MessageBox.Show("Bạn có thật sự muốn xóa?","Xóa Sim",MessageBoxButtons.YesNo,MessageBoxIcon.Question)==DialogResult.Yes)
            {
                try
                {
                    SimDao s = new SimDao();
                    s.XoaSim(txt_MaSim.Text);
                    simpleButton1_Click(sender, e);
                    MessageBox.Show("Xóa Thành Công");
                    this.refresh();
                    txt_MaSim.Text = "";
                    txt_SoSim.Text = "";
                }
                 catch (Exception ex)
                {
                    MessageBox.Show("Sim Đang Được Sử Dụng Không Thể Xóa Được");
                }
            }
            
        }

        private void textEdit1_TextChanged(object sender, EventArgs e)
        {
            gridView1.FindFilterText = textEdit1.Text;
        }
    }
}
